version: '3.0'
services:
  rasa:
    container_name: "rasa_server"
    build:
      context: .
    ports:
    - 5005:5005
    volumes:
    - ./:/app
    command:
      - run


  action-server:
    container_name: "action_server"
    build:
      context: actions
    volumes:
    - ./actions:/app/actions
    ports:
    - 5055:5055

  rasa_x:
    container_name: "rasa-x"
    image: rasa/rasa-x:latest
    ports:
    - 5002:5002
    command:
      - rasa x --no-prompts

  duckling:
    restart: always
    image: "rasa/duckling:latest"
    ports:
      - "8000:8000"
    command: [ "duckling-example-exe", "--no-access-log", "--no-error-log" ]